version: '3.8'

services:
  app:
    image: nestjs-postgresql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      POSTGRES_HOST: ${DOCKER_HOST}
      POSTGRES_PORT: ${DOCKER_PORT}
      POSTGRES_USER: ${DOCKER_USER}
      POSTGRES_PASSWORD: ${DOCKER_PASSWORD}
      POSTGRES_DB: ${DOCKER_DATABASE}
